//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.AdminUserMeetingRelations = new HashSet<AdminUserMeetingRelation>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int admin_id { get; set; }
        public System.DateTime meeting_date { get; set; }
        public System.TimeSpan time_start { get; set; }
        public System.TimeSpan time_end { get; set; }
        public string duration { get; set; }
        public int approval { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUserMeetingRelation> AdminUserMeetingRelations { get; set; }
    }
}
