//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public System.DateTime visit_date { get; set; }
        public System.TimeSpan time_start { get; set; }
        public int approval { get; set; }
        public int status { get; set; }
        public string qrcode { get; set; }
        public string purpose { get; set; }
    
        public virtual user user1 { get; set; }
    }
}
